### PR TITLE
feat deploy with travis

### PR DESCRIPTION
**Pull request by lohanidamodar**

### CODE REVIEW

**Review by kodumbeats — APPROVED** [review]

**Comment by eldadfux** [comment]
Tests are failing 😧

**Comment by eldadfux** [comment]
Tests are still failing

**Comment by lohanidamodar** [comment]
@eldadfux tests are passing after skipping S390x

**Review by kodumbeats — APPROVED** [review]

**Comment by Izzy1970** [comment]
Domuzun dölû 🤟


Regards Meral 

On Wednesday, June 9, 2021, 11:24 pm, Eldad A. Fux ***@***.***> wrote:




Tests are failing 😧

**Pull request merged**
