### PR TITLE
Upgrade from Alpine 3.12 to 3.14

### PR DESCRIPTION
**Pull request by gaby**
* Upgrade to latest available Alpine Linux

### CODE REVIEW

**Comment by eldadfux** [comment]
Restarted tests

**Comment by gaby** [comment]
Travis CI is so bad, it fails on the most random stuff.

**Comment by eldadfux** [comment]
Seems like there was an issue with `S390x` that was fixed on #10. @gaby please sync with master and tests should be green.

**Comment by Izzy1970** [comment]
can you stop messaging me 
i have nothing to do with this

Regards 
Meral Yalcin


On 2 Nov 2021, at 4:55 pm, Juan Calderon-Perez ***@***.***> wrote:

﻿
Travis CI is so bad, it fails on the most random stuff.

**Comment by Izzy1970** [comment]
stop emailing me 

Regards 
Meral Yalcin


On 2 Nov 2021, at 5:00 pm, Eldad A. Fux ***@***.***> wrote:

﻿
Seems like there was an issue with S390x that was fixed on #10. @gaby please sync with master and tests should be green.

**Pull request closed without merging**
